// Import createSlice and PayloadAction from Redux Toolkit
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the interface for the navbar state
interface NavbarState {
  navbarText: string;
}

const initialNavbarText = sessionStorage.getItem("navbarText") || "Dashboard";

// Define the initial state for the navbar slice
const initialState: NavbarState = {
  navbarText: initialNavbarText, // Set the initial navbar text
};

// Create a slice for managing navbar state
const navbarSlice = createSlice({
  name: "navbar",
  initialState,
  reducers: {
    // Reducer function to update the navbar text
    updateNavbarText: (state, action: PayloadAction<string>) => {
      // Update navbar text to the payload received and store it in sessionStorage
      state.navbarText = action.payload;
      sessionStorage.setItem("navbarText", action.payload);
    },
  },
});

// Extract and export the action creator
export const { updateNavbarText } = navbarSlice.actions;

// Export the reducer function generated by createSlice
export default navbarSlice.reducer;
